services:
  postgres:
    image: postgres:16
    container_name: devradar_postgres
    environment:
      POSTGRES_USER: devradar
      POSTGRES_PASSWORD: devradar
      POSTGRES_DB: devradar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: devradar_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: